In [5]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error


data = pd.read_csv('/content/test.csv')
data_description = data.describe()
print("Data Description:\n", data_description)


print("\nData Types of Each Column:\n", data.dtypes)
print("\nShape of Data:", data.shape)


null_values = data.isnull().sum()
print("\nNull Values:\n", null_values)
data.fillna(0, inplace=True)

Data Description:
                 id  battery_power         blue  clock_speed     dual_sim  \
count  1000.000000    1000.000000  1000.000000  1000.000000  1000.000000
mean    500.500000    1248.510000     0.516000     1.540900     0.517000
std     288.819436     432.458227     0.499994     0.829268     0.499961
min       1.000000     500.000000     0.000000     0.500000     0.000000
25%     250.750000     895.000000     0.000000     0.700000     0.000000
50%     500.500000    1246.500000     1.000000     1.500000     1.000000
75%     750.250000    1629.250000     1.000000     2.300000     1.000000
max    1000.000000    1999.000000     1.000000     3.000000     1.000000

                fc       four_g   int_memory        m_dep   mobile_wt  ...  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.00000  ...
mean      4.593000     0.487000    33.652000     0.517500   139.51100  ...
std       4.463325     0.500081    18.128694     0.280861    34.85155  ...
min       0.000000     0.000000     2.000000     0.100000    80.00000  ...
25%       1.000000     0.000000    18.000000     0.300000   109.75000  ...
50%       3.000000     0.000000    34.500000     0.500000   139.00000  ...
75%       7.000000     1.000000    49.000000     0.800000   170.00000  ...
max      19.000000     1.000000    64.000000     1.000000   200.00000  ...

                pc    px_height     px_width          ram         sc_h  \
count  1000.000000  1000.000000  1000.000000  1000.000000  1000.000000
mean     10.054000   627.121000  1239.774000  2138.998000    11.995000
std       6.095099   432.929699   439.670981  1088.092278     4.320607
min       0.000000     0.000000   501.000000   263.000000     5.000000
25%       5.000000   263.750000   831.750000  1237.250000     8.000000
50%      10.000000   564.500000  1250.000000  2153.500000    12.000000
75%      16.000000   903.000000  1637.750000  3065.500000    16.000000
max      20.000000  1907.000000  1998.000000  3989.000000    19.000000

              sc_w    talk_time      three_g  touch_screen         wifi
count  1000.000000  1000.000000  1000.000000    1000.00000  1000.000000
mean      5.316000    11.085000     0.756000       0.50000     0.507000
std       4.240062     5.497636     0.429708       0.50025     0.500201
min       0.000000     2.000000     0.000000       0.00000     0.000000
25%       2.000000     6.750000     1.000000       0.00000     0.000000
50%       5.000000    11.000000     1.000000       0.50000     1.000000
75%       8.000000    16.000000     1.000000       1.00000     1.000000
max      18.000000    20.000000     1.000000       1.00000     1.000000

[8 rows x 21 columns]

Data Types of Each Column:
 id                 int64
battery_power      int64
blue               int64
clock_speed      float64
dual_sim           int64
fc                 int64
four_g             int64
int_memory         int64
m_dep            float64
mobile_wt          int64
n_cores            int64
pc                 int64
px_height          int64
px_width           int64
ram                int64
sc_h               int64
sc_w               int64
talk_time          int64
three_g            int64
touch_screen       int64
wifi               int64
dtype: object

Shape of Data: (1000, 21)

Null Values:
 id               0
battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
dtype: int64

In [ ]:
X = data.drop(columns=['target_column_name'])
y = data['target_column_name']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


scaler = MinMaxScaler()
â€¦rmse = np.sqrt(mse)

print("\nMean Squared Error:", mse)
print("Mean Absolute Error:", mae)
print("Root Mean Squared Error:", rmse)


w_values = model.coef_
print("\nCoefficients (w values):", w_values)

In [8]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error


data = pd.read_csv('/content/housing.csv')
data_description = data.describe()
print("Data Description:\n", data_description)


print("\nData Types of Each Column:\n", data.dtypes)
print("\nShape of Data:", data.shape)


null_values = data.isnull().sum()
print("\nNull Values:\n", null_values)
data.fillna(0, inplace=True)

Data Description:
           longitude      latitude  housing_median_age   total_rooms  \
count  20640.000000  20640.000000        20640.000000  20640.000000
mean    -119.569704     35.631861           28.639486   2635.763081
std        2.003532      2.135952           12.585558   2181.615252
min     -124.350000     32.540000            1.000000      2.000000
25%     -121.800000     33.930000           18.000000   1447.750000
50%     -118.490000     34.260000           29.000000   2127.000000
75%     -118.010000     37.710000           37.000000   3148.000000
max     -114.310000     41.950000           52.000000  39320.000000

       total_bedrooms    population    households  median_income  \
count    20433.000000  20640.000000  20640.000000   20640.000000
mean       537.870553   1425.476744    499.539680       3.870671
std        421.385070   1132.462122    382.329753       1.899822
min          1.000000      3.000000      1.000000       0.499900
25%        296.000000    787.000000    280.000000       2.563400
50%        435.000000   1166.000000    409.000000       3.534800
75%        647.000000   1725.000000    605.000000       4.743250
max       6445.000000  35682.000000   6082.000000      15.000100

       median_house_value
count        20640.000000
mean        206855.816909
std         115395.615874
min          14999.000000
25%         119600.000000
50%         179700.000000
75%         264725.000000
max         500001.000000

Data Types of Each Column:
 longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

Shape of Data: (20640, 10)

Null Values:
 longitude               0
latitude                0
housing_median_age      0
total_rooms             0
total_bedrooms        207
population              0
households              0
median_income           0
median_house_value      0
ocean_proximity         0
dtype: int64